name: Prebuild Binaries

on:
  push:
    tags:        
      - v*

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      test: some text
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: true
      - name: Debug
        run: |
          echo ${{ steps.create_release.outputs.upload_url }}
          echo ${{ create_release.outputs.upload_url }}

  prebuild-linux:
    name: Prebuild Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Install Toolchain
        run: sudo apt-get install g++-multilib
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Checkout and Build
        uses: actions/checkout@v1
      - name: Set Env
        run: |
          echo ::set-env name=TAG::${GITHUB_REF#refs/tags/}
          echo ::set-env name=FILENAME::${TAG}-linux-x86_64.tar
          echo ::set-env name=UPLOAD_URL::${{ needs.create_release.outputs.upload_url }}
          echo TAG: ${{ env.TAG }}
          echo FILENAME: ${{ env.FILENAME }}
          echo UPLOAD_URL: ${{ env.UPLOAD_URL }}
      - run: npm install
      - run: npm run prebuild
      - run: tar --create --verbose --file=${FILENAME} --directory ./prebuilds .
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./${{ env.FILENAME }}
          asset_name: ${{ env.FILENAME }}
          asset_content_type: application/tar
