name: Prebuild Binaries

on:
  push:
    tags:        
      - v*

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: true

  prebuild-linux:
    name: Prebuild Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env: 
      UPLOAD_URL: ${{ needs.create_release.outputs.upload_url }}
    steps:
      - name: Install Toolchain
        run: sudo apt-get install g++-multilib
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Checkout and Build
        uses: actions/checkout@v1
      - run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - run: echo $TAG - $UPLOAD_URL
      - run: npm install
      - run: npm run prebuild
      - run: tar --create --verbose --file="${TAG}-linux-x86_64.tar" --directory "./prebuilds" .
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${UPLOAD_URL}  
          asset_path: "./${TAG}-linux-x86_64.tar"
          asset_name: "${TAG}-linux-x86_64.tar"
          asset_content_type: application/tar
