name: Prebuild Binaries

on:
  push:
    branches:
      - refs/tags/*

jobs:
  prebuild-linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - run: sudo apt-get install g++-multilib
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - run: npm install
      - run: npx prebuild --runtime napi --all --strip --verbose --upload ${{ secrets.GITHUB_TOKEN }}
      - run: npx prebuild --runtime napi --all --strip --verbose --upload ${{ secrets.GITHUB_TOKEN }} -a ia32

  prebuild-macos:
    name: macOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - run: npm install
      - run: npx prebuild --runtime napi --all --strip --verbose --upload ${{ secrets.GITHUB_TOKEN }}

  prebuild-windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v1
      - run: npm install
      - run: npx prebuild --runtime napi --all --strip --verbose --upload ${{ secrets.GITHUB_TOKEN }}
      - run: npx prebuild --runtime napi --all --strip --verbose --upload ${{ secrets.GITHUB_TOKEN }} -a ia32
