name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * 0"

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Environment Information
        run: npx envinfo
      - name: Run Test
        run: npm test
